# Generated by Django 3.1.4 on 2021-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('legs', 'Ноги'), ('hands', 'Руки'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('chest', 'Грудь')], default='hands', max_length=20),
        ),
    ]
