# Generated by Django 3.2.6 on 2021-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0004_auto_20210828_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapparatus',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
