# Generated by Django 3.2.6 on 2021-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0005_trainingapparatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpart',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
