# Generated by Django 3.2.6 on 2022-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0006_workoutpart_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('free', 'Свободная'), ('in_process', 'В процессе'), ('completed', 'Завершенная')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutpart',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
