# Generated by Django 3.2.6 on 2022-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0007_auto_20220117_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='in_process',
        ),
        migrations.AlterField(
            model_name='workoutpart',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
