# Generated by Django 3.2.6 on 2022-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0008_auto_20220117_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['status', 'date']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[(1, 'Свободная'), (2, 'В процессе'), (3, 'Завершенная')], default='free', max_length=20),
        ),
    ]
