# Generated by Django 3.2.6 on 2022-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0009_auto_20220122_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[(1, 'Свободная'), (2, 'В процессе'), (3, 'Завершенная')], default=1, max_length=20),
        ),
    ]
