# Generated by Django 3.2.6 on 2022-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0010_alter_workout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapparatus',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('b', 'Свободная'), ('a', 'В процессе'), ('c', 'Завершенная')], default='b', max_length=20),
        ),
    ]
