# Generated by Django 3.2.6 on 2022-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymWorkoutApp', '0011_auto_20220122_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingapparatus',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
